#  **Classification Simulator**

## Imports

In [15]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier

## Import files

In [3]:
predictor = pd.read_csv('/content/drive/MyDrive/curso_ML/Treinamento/Classificacao/Desafio/Database/predictor.csv', header=None)

In [11]:
target = pd.read_csv('/content/drive/MyDrive/curso_ML/Treinamento/Classificacao/Desafio/Database/target.csv', header=None)

## Verify files details

In [5]:
predictor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,0.9053,0.01587,25.380,17.33,184.60,0.16220,0.66560,0.2654,0.4601
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.7339,0.01340,24.990,23.41,158.80,0.12380,0.18660,0.1860,0.2750
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7869,0.02058,23.570,25.53,152.50,0.14440,0.42450,0.2430,0.3613
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,1.1560,0.01867,14.910,26.50,98.87,0.20980,0.86630,0.2575,0.6638
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7813,0.01885,22.540,16.67,152.20,0.13740,0.20500,0.1625,0.2364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.2560,0.02454,25.450,26.40,166.10,0.14100,0.21130,0.2216,0.2060
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,2.4630,0.01678,23.690,38.25,155.00,0.11660,0.19220,0.1628,0.2572
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,1.0750,0.01557,18.980,34.12,126.70,0.11390,0.30940,0.1418,0.2218
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,1.5950,0.01664,25.740,39.42,184.60,0.16500,0.86810,0.2650,0.4087
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,1.4280,0.00000,9.456,30.37,59.16,0.08996,0.06444,0.0000,0.2871

In [12]:
target

       0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
..   ...
564  0.0
565  0.0
566  0.0
567  0.0
568  1.0

[569 rows x 1 columns]

## Convert Datas

In [7]:
predictor = predictor.values
predictor

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 6.656e-01, 2.654e-01,
        4.601e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.866e-01, 1.860e-01,
        2.750e-01],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 4.245e-01, 2.430e-01,
        3.613e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 3.094e-01, 1.418e-01,
        2.218e-01],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 8.681e-01, 2.650e-01,
        4.087e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 6.444e-02, 0.000e+00,
        2.871e-01]])

In [17]:
predictor.shape

(569, 19)

In [13]:
target = target.iloc[:, 0].values
target

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1.])

## Execute XGBOOST Algorithm

In [64]:
xg = XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)
xg.fit(predictor, target)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.075, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=3, ...)

In [65]:
patient1 = [14.13, 19.29, 91.97, 654.89, 0.10, 0.10, 0.09, 0.05, 0.18, 0.06, 1.22, 0.01, 16.27, 25.68, 107.26, 0.13, 0.25, 0.11, 0.29]
patient1 = np.asarray(patient1).reshape(1, -1)

In [66]:
patient2 = [20.60, 29.33, 140.10, 1265.00, 0.12, 0.28, 0.35, 0.15, 0.24, 0.07, 1.59, 0.02, 25.74, 39.42, 184.60, 0.17, 0.87, 0.27, 0.41]
patient2 = np.asarray(patient2).reshape(1, -1)

In [67]:
patient3 = [28.11, 39.28, 188.50, 2501.00, 0.16, 0.35, 0.43, 0.20, 0.30, 0.10, 4.88, 0.05, 36.04, 49.54, 251.20, 0.22, 1.06, 0.29, 0.66]
patient3 = np.asarray(patient3).reshape(1, -1)

In [68]:
patient4 = [17.99, 10.38, 122.80, 1001.00, 0.12, 0.28, 0.30, 0.15, 0.24, 0.08, 0.91, 0.02, 25.38, 17.33, 184.60, 0.16, 0.67, 0.27, 0.46]
patient4 = np.asarray(patient4).reshape(1, -1)

In [69]:
patient5 = [11.42, 20.38, 77.58, 386.10, 0.14, 0.28, 0.24, 0.11, 0.26, 0.10, 1.16, 0.02, 14.91, 26.50, 98.87, 0.21, 0.87, 0.26, 0.66]
patient5 = np.asarray(patient5).reshape(1, -1)

In [70]:
patient6 = [16.60, 28.08, 108.30, 858.10, 0.08, 0.10, 0.09, 0.05, 0.16, 0.06, 1.07, 0.02, 18.98, 34.12, 126.70, 0.11, 0.31, 0.14, 0.22]
patient6 = np.asarray(patient6).reshape(1, -1)

In [71]:
patient7 = [20.60, 29.33, 140.10, 1265.00, 0.12, 0.28, 0.35, 0.15, 0.24, 0.07, 1.59, 0.02, 25.74, 39.42, 184.60, 0.17, 0.87, 0.27, 0.41]
patient7 = np.asarray(patient7).reshape(1, -1)

In [72]:
patient8 = [15.73, 11.28, 102.80, 747.20, 0.10, 0.13, 0.12, 0.06, 0.18, 0.06, 0.39, 0.01, 17.01, 14.20, 112.50, 0.15, 0.30, 0.15, 0.26]
patient8 = np.asarray(patient8).reshape(1, -1)

In [73]:
patient9 = [15.46, 23.95, 103.80, 731.30, 0.12, 0.19, 0.20, 0.09, 0.18, 0.07, 1.96, 0.02, 17.11, 36.33, 117.70, 0.17, 0.50, 0.22, 0.30]
patient9 = np.asarray(patient9).reshape(1, -1)

In [74]:
patient10 = [12.46, 24.04, 83.97, 475.90, 0.12, 0.24, 0.23, 0.09, 0.20, 0.08, 1.60, 0.01, 15.09, 40.68, 97.65, 0.19, 1.06, 0.22, 0.44]
patient10 = np.asarray(patient10).reshape(1, -1)

In [95]:
result = xg.predict(patient10)

In [96]:
if result == 1:
    print('The patient HAS a tendency for malignant conditions.')
else:
    print('The patient DOES NOT HAVE a tendency for malignant conditions.')

The patient DOES NOT HAVE a tendency for malignant conditions.