In [2]:
import pandas as pd
import glob

In [24]:
arquivos = ['brasileirao_2023_completo.csv', 'brasileirao_2024_completo.csv', 'brasileirao_2025_completo.csv']

In [25]:
lista_df = [pd.read_csv(f) for f in arquivos]

In [26]:
df_final = pd.concat(lista_df, ignore_index=True)
df_final.head()

,Temporada,Rodada,Partida,Jogador,Time,Sigla_Tatica,Posicao_Final,totalPass,accuratePass,totalLongBalls,...,crossNotClaimed,clearanceOffLine,ownGoals,lastManTackle,totalBallCarriesDistance,ballCarriesCount,totalProgression,bestBallCarryProgression,totalProgressiveBallCarriesDistance,progressiveBallCarriesCount
0,2023,1,América Mineiro x Fluminense,Matheus Cavichioli,América Mineiro,G,Outro,19.0,9.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,1,América Mineiro x Fluminense,Nino Paraíba,América Mineiro,D,Outro,29.0,19.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,1,América Mineiro x Fluminense,Éder,América Mineiro,D,Outro,35.0,25.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,1,América Mineiro x Fluminense,Iago Maidana,América Mineiro,D,Outro,18.0,15.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,1,América Mineiro x Fluminense,Marlon Lopes,América Mineiro,D,Outro,32.0,26.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_final.describe()

,Temporada,Rodada,totalPass,accuratePass,totalLongBalls,accurateLongBalls,accurateOwnHalfPasses,totalOwnHalfPasses,totalOppositionHalfPasses,totalClearance,...,crossNotClaimed,clearanceOffLine,ownGoals,lastManTackle,totalBallCarriesDistance,ballCarriesCount,totalProgression,bestBallCarryProgression,totalProgressiveBallCarriesDistance,progressiveBallCarriesCount
count,52085.000000,52085.000000,35529.000000,35268.000000,25814.000000,20913.000000,33239.000000,33751.000000,34993.000000,18424.000000,...,32.000000,172.000000,65.0,204.000000,1396.000000,1396.000000,1396.000000,1396.000000,16.000000,16.000000
mean,2023.999789,19.496131,27.103352,22.667432,4.348299,2.673839,12.073167,13.215194,15.865316,2.617564,...,1.062500,1.005814,1.0,1.029412,90.430028,10.800860,4.184130,10.795745,47.162065,2.187500
std,0.817441,10.964112,19.478922,17.693001,4.170473,2.137939,11.002910,11.659348,11.692914,2.201604,...,0.245935,0.076249,0.0,0.169373,73.434411,8.416345,63.511565,10.264493,28.552901,1.796988
min,2023.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,1.000000,1.000000,1.0,1.000000,3.021364,1.000000,-438.795000,-19.215000,20.685447,1.000000
25%,2023.000000,10.000000,12.000000,9.000000,1.000000,1.000000,4.000000,4.000000,7.000000,1.000000,...,1.000000,1.000000,1.0,1.000000,33.271740,4.000000,-23.730000,3.990000,27.974676,1.000000
50%,2024.000000,20.000000,23.000000,18.000000,3.000000,2.000000,9.000000,10.000000,13.000000,2.000000,...,1.000000,1.000000,1.0,1.000000,73.823811,9.000000,1.522500,8.085000,38.923622,2.000000
75%,2025.000000,29.000000,38.000000,32.000000,6.000000,3.000000,17.000000,19.000000,22.000000,3.000000,...,1.000000,1.000000,1.0,1.000000,127.922379,15.000000,32.156250,15.960000,55.434986,2.250000
max,2025.000000,38.000000,139.000000,132.000000,40.000000,21.000000,88.000000,90.000000,110.000000,23.000000,...,2.000000,2.000000,1.0,2.000000,645.364208,70.000000,471.135000,58.170000,133.437051,8.000000

In [27]:
nulos_por_coluna = df_final.isnull().sum()

total_linhas = len(df_final)

resumo_nan = pd.DataFrame({
    'Total NaN': nulos_por_coluna,
    'Total Linhas': total_linhas,
    'Percentual (%)': (nulos_por_coluna / total_linhas) * 100
})

print(resumo_nan)

                                     Total NaN  Total Linhas  Percentual (%)
Temporada                                    0         52085        0.000000
Rodada                                       0         52085        0.000000
Partida                                      0         52085        0.000000
Jogador                                      0         52085        0.000000
Time                                         0         52085        0.000000
...                                        ...           ...             ...
ballCarriesCount                         50689         52085       97.319766
totalProgression                         50689         52085       97.319766
bestBallCarryProgression                 50689         52085       97.319766
totalProgressiveBallCarriesDistance      52069         52085       99.969281
progressiveBallCarriesCount              52069         52085       99.969281

[78 rows x 3 columns]

In [29]:
df_final['Time'].unique()

array(['América Mineiro', 'Fluminense', 'Palmeiras', 'Cuiabá',
       'Athletico', 'Goiás', 'Botafogo', 'São Paulo', 'Fortaleza',
       'Internacional', 'Red Bull Bragantino', 'Bahia',
       'Atlético Mineiro', 'Vasco da Gama', 'Corinthians', 'Cruzeiro',
       'Flamengo', 'Coritiba', 'Grêmio', 'Santos', 'Criciúma',
       'Juventude', 'Atlético Goianiense', 'Vitória', 'Mirassol',
       'Sport Recife', 'Ceará'], dtype=object)

In [30]:
df_final['Time'].value_counts()

Time
Grêmio                 2622
Vasco da Gama          2621
Fortaleza              2619
Bahia                  2619
Red Bull Bragantino    2617
Fluminense             2617
Corinthians            2616
Flamengo               2616
Cruzeiro               2614
São Paulo              2610
Botafogo               2605
Internacional          2598
Palmeiras              2594
Atlético Mineiro       2557
Santos                 1748
Athletico              1744
Juventude              1743
Vitória                1742
Cuiabá                 1725
Criciúma                872
América Mineiro         871
Ceará                   868
Coritiba                868
Mirassol                868
Goiás                   862
Sport Recife            860
Atlético Goianiense     789
Name: count, dtype: int64

In [33]:
df_final['Sigla_Tatica'].unique()

array(['G', 'D', 'M', 'F', nan], dtype=object)