In [1]:
import pandas as pd
import numpy as np

In [2]:
independente = pd.read_csv('/content/drive/MyDrive/curso_ML/Treinamento/Regressão/Aulas/Database/independente.csv', header=None)

In [3]:
independente

         0     1     2
0    6.575  4.98  15.3
1    6.421  9.14  17.8
2    7.185  4.03  17.8
3    6.998  2.94  18.7
4    7.147  5.33  18.7
..     ...   ...   ...
484  6.593  9.67  21.0
485  6.120  9.08  21.0
486  6.976  5.64  21.0
487  6.794  6.48  21.0
488  6.030  7.88  21.0

[489 rows x 3 columns]

In [4]:
independente = independente.values

In [5]:
dependente = pd.read_csv('/content/drive/MyDrive/curso_ML/Treinamento/Regressão/Aulas/Database/dependente.csv', header=None)

In [6]:
dependente

            0
0    504000.0
1    453600.0
2    728700.0
3    701400.0
4    760200.0
..        ...
484  470400.0
485  432600.0
486  501900.0
487  462000.0
488  249900.0

[489 rows x 1 columns]

In [7]:
dependente = dependente.iloc[:, 0].values

In [8]:
from sklearn.ensemble import RandomForestRegressor
random = RandomForestRegressor(n_estimators = 60, criterion = 'squared_error', max_depth = 5, random_state = 10)
random.fit(independente, dependente)

RandomForestRegressor(max_depth=5, n_estimators=60, random_state=10)

In [18]:
RM = input('Qual o número de cômodos? R: ')

Qual o número de cômodos? R: 10

In [19]:
LSTAT = input('Qual a porcentagem de proprietários de classe baixa? R: ')

Qual a porcentagem de proprietários de classe baixa? R: 50

In [20]:
PTRATIO = input('Qual a razão entre o número de estudantes e professores? R: ')

Qual a razão entre o número de estudantes e professores? R: 2

In [21]:
informacoes = [RM, LSTAT, PTRATIO]
valor_casa = random.predict([informacoes])
print('O valor da casas é de US$ {:.2f}'.format(valor_casa[0]))

O valor da casas é de US$ 563088.11